# Generated by Django 5.0.3 on 2024-03-30 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 0, 20, 33, 288155, tzinfo=datetime.timezone.utc)),
        ),
    ]
